<a href="https://colab.research.google.com/github/polina-minaeva/advanced-linear-algebra/blob/main/%D0%94%D0%97%20%22%D0%9F%D1%80%D0%BE%D0%B4%D0%B2%D0%B8%D0%BD%D1%83%D1%82%D0%B0%D1%8F%20%D0%BB%D0%B8%D0%BD%D0%B5%D0%B9%D0%BD%D0%B0%D1%8F%20%D0%B0%D0%BB%D0%B3%D0%B5%D0%B1%D1%80%D0%B0%22.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Задание. Найдите спектральное разложение матрицы:

In [ ]:
import numpy as np #импорт библиотеки
m = np.array([[1, 2],
              [2, 3]])

In [ ]:
ev, eW = np.linalg.eigh(m) #находим собственные значения и векторы симметричной матрицы
ev, eW

(array([-0.23606798,  4.23606798]),
 array([[-0.85065081,  0.52573111],
        [ 0.52573111,  0.85065081]]))

In [ ]:
L=np.diag(ev) #создаем диагональную матрицу из собственных значений
L

array([[-0.23606798,  0.        ],
       [ 0.        ,  4.23606798]])

In [ ]:
#теперь нужно получить две ортогональные матрицы, состоящие из собственных векторов

m2 = eW.T
m2

array([[-0.85065081,  0.52573111],
       [ 0.52573111,  0.85065081]])

In [ ]:
m3 = m2.T
m3

array([[-0.85065081,  0.52573111],
       [ 0.52573111,  0.85065081]])

In [ ]:
#убедимся, что матрицы ортогональны

np.dot(m2, m3)

array([[ 1.0000000e+00, -1.2127222e-17],
       [-1.2127222e-17,  1.0000000e+00]])

In [ ]:
np.dot(np.dot(m3, L), m2) #при умножении диагональной матрицы, матрицы из собственных векторов и матрицы, обратной ей, получаем исходную матрицу m

array([[1., 2.],
       [2., 3.]])